### ISSUE TITLE
Behavior todo list

### ISSUE THREAD

**Issue by WJWang** [WJWang/ios-behavior-sample#1]
- [ ] calendar access
- [ ] adressbook access
- [ ] locations
- [ ] bluetooth
- [ ] UIDocumentInteract(AirDrop, share)
- [ ] microphone
- [ ] camera roll
- [ ] iAd
- [ ] in app purchase
- [ ] FB, Google, Line SDK used
- [ ] AWS Service, HiCloud ...
- [ ] HTTP/HTTPS/FTP
- [ ] sqlite, coredata, userdefault, filemanager
